### ISSUE TITLE
Do you have a sample example code to use mdbx?

### ISSUE THREAD

**Issue by hiqsociety** [torquem-ch/mdbx-go#2]
e.g.
        "github.com/torquem-ch/mdbx-go/mdbx"

and then what?

mdbx.Open() <- this is not working. How do you use the DBI? I'm converting boltdb to use this. Can you help?

**Comment by AskAlexSharov** [comment]
hi. just open any _test.go file and use it as an example:
https://github.com/torquem-ch/mdbx-go/blob/master/mdbx/mdbx_test.go
https://github.com/torquem-ch/mdbx-go/blob/master/mdbx/cursor_test.go

**Comment by AskAlexSharov** [comment]
Made release: https://github.com/torquem-ch/mdbx-go/releases/tag/v0.9.3
Added some info about building: https://github.com/torquem-ch/mdbx-go/blob/master/README.md#build

**Comment by hiqsociety** [comment]
great! we just need "go get" and it's complete. well done!

**Comment by AskAlexSharov** [comment]
Please read building info:  https://github.com/torquem-ch/mdbx-go/blob/master/README.md#build
It can't be used by "go get" because - it's hard to build libmdbx by CGO - so, for now we building mdbx by mdbx's Makefile. It creating config.h file on the fly (by checking various system components/libs/compilers/...) - CGO can't do it, also it collecting more info than CGO can provide (or maybe I just don't know how to get it by CGO).
